export const Product = [
  {
    id: 1,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 30,
  },
  {
    id: 2,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 40,
  },
  {
    id: 3,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 10,
  },
  {
    id: 4,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 50,
  },
  {
    id: 5,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 22,
  },
  {
    id: 6,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 72,
  },
  {
    id: 7,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 52,
  },
  {
    id: 8,
    img: require('../assets/collections/3.webp'),
    title: 'Ultraboost 22 Shoes',
    description: `Men's Runnings`,
    rating: 'best seller',
    price: 100,
  },
];
