export const Service = [
  {
    id: 1,
    img: require('../assets/collections/4.webp'),
    title: 'STAN SMITH',
    description: 'Endless ways to embody your style.',
    link: 'Shop Now',
  },
  {
    id: 2,
    img: require('../assets/collections/5.jpeg'),
    title: 'RUN FOR THE OCEANS',
    description:
      'Every action counts. Discover our Run For The Oceans collection, made to help end plastic waste.',
    link: 'Shop Now',
  },
  {
    id: 3,
    img: require('../assets/collections/6.webp'),
    title: 'THE SUMMER SHOP',
    description: 'Cool styles to kick off summer fun.',
    link: 'Shop Now',
  },
  {
    id: 4,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
  {
    id: 5,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
  {
    id: 6,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
  {
    id: 7,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
  {
    id: 8,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
  {
    id: 9,
    img: require('../assets/collections/7.jpeg'),
    title: 'SUPPORT IS EVERYTHING',
    description: 'Inclusive sports bras and tights for every body, every move.',
    link: 'Shop Now',
  },
];
